replicaCount: 2
nameOverride: demo

image:
  repository: sakuard/node-service
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "16m"
    memory: "128Mi"
  requests:
    cpu: "8m"
    memory: "64Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: false
  name: default