apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-service.fullname" . }}-svc
  labels:
    {{- include "node-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "node-service.selectorLabels" . | nindent 4 }}